# Generated by Django 2.0.1 on 2018-01-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_phone', models.CharField(max_length=11)),
                ('from_name', models.CharField(max_length=50)),
                ('from_phone', models.CharField(max_length=11)),
                ('to_name', models.CharField(max_length=50)),
                ('to_phone', models.CharField(max_length=11)),
                ('to_address', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('grade', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-order_date',),
            },
        ),
    ]
